### ISSUE TITLE
Duplicate values are not overridden using .toObject()

### ISSUE THREAD

**Issue by Anyasia** [drslump/Ini-js#4]
Presently, calling `.toObject()` on an `Ini` object with duplicate properties causes the initial value to be passed, rather than the newer one.

``` javascript
var ini = new Ini();

ini.parse([
    'prop = value',
    '[sect]',
    'foo = bar',
    'baz = yes',
    '[sect "label"]',
    'foo = "bar"',
    'baz = off'
].join('\n'));

ini.get('sect').property('foo', 'quux');

ini.get('sect.foo'); // quux

ini.toObject().sect.foo; // bar
```

This is caused by `Ini.Section.prototype.toObject` iterating in reverse order. While this is the desired behavior for `Ini.Section.prototype.get`, since it only returns once, `.toObject()` continues iterating after the first occurrence, so a property is first set to its final declared value but is then overridden by previously-declared values, until only its initial value remains.

This can be solved by iterating normally, rather than in reverse:

``` javascript
Ini.Section.prototype.toObject = function(){
    var i, o = {}, items = this.items;

    // Looping in reverse order prevents duplicate key override in this case,
    // so instead we're looping normally
    i = 0;
    while (i < items.length) {
        if (items[i] instanceof Ini.Section) {
            o[items[i].key] = items[i].toObject();
        }
        if (items[i] instanceof Ini.Property) {
            o[items[i].key] = items[i].value;
        }
        i++;
    }
    return o;
};
```

Forgive me if this is not the proper way to file a bug report; I'm not overly-familiar with the proper procedures for using GitHub.

**Comment by drslump** [comment]
Thanks for the detailed report @Anyasia.
